name: update-addons-LE12-own-branch
on:
  workflow_dispatch:
jobs:
  update_addon_repo:
    name: Update Addon Repo
    runs-on: ubuntu-latest
    env: 
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: libreelec-12.0
          fetch-depth: 2
          repository: "LibreELECBot/LibreELEC.tv"
      - name: Update Binary Addons
        id: update_binary_addons
        run: |
          echo "Updating Add-on version ${{ github.event.inputs.input_addon-version }}"
          export GITHUB_API_TOKEN="$GH_API_KEY"
          temp_file=$(mktemp)
          ./tools/mkpkg/update_binary-addons -x master | tee "${temp_file}"
          git_commit_msg=$(cat ${temp_file} | grep "^UPDATED " | sed 's/^UPDATED /- /' | sed 's/ from /: update /')
          echo "git_commit_msg<<EOF" >> $GITHUB_OUTPUT
          echo "${git_commit_msg}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "-------------------!-------------------"
          echo "${temp_file"
          echo "-------------------!-------------------"

      - name: Get SHA of the branch that triggered the workflow run
        id: head_branch
        run: |
          sha=$(git rev-parse HEAD)
          echo "sha=${sha}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.LIBREELECBOT_GITHUB_TOKEN }}
          commit-message: |
            [LE12] kodi-binary-addons: update to latest versions

            This commit updates kodi-binary-addons with ./tools/mkpkg/update_binary-addons

            ${{ steps.update_binary_addons.outputs.git_commit_msg }}
          committer: LibreELEC Bot <libreelec-bot@libreelec.tv>
          author: LibreELEC Bot <libreelec-bot@libreelec.tv>
          reviewers: LibreELEC Bot <libreelec-bot@libreelec.tv>
          labels: 'github-action'
          signoff: false
          branch: 12.0/pr_binary_addons
          delete-branch: true
          title: "kodi-binary-addons: update to latest versions"
          body: |
            This pull-request was auto-generated by the [updater-LE12][1] GitHub action workflow.
          draft: false
          add-paths: |
            packages/mediacenter/kodi-binary-addons

      - name: Clean up
        run: |
          rm -f "${temp_file}"
